### ISSUE TITLE
Interrupting a tlet binding

### ISSUE THREAD

**Issue by timothypratley** [leonoel/task#1]
Is there a way to stop a tlet chain:

```
(t/do!! (t/tlet [a (t/timeout 1000 6)
                 b (t/timeout 1000 (inc a))]
          (* a b)))                              ;; returns 42 after 2 seconds
```

But after 1 second I want to cancel the chain? (Because the tasks are no longer required)

This scenario comes up from me in animation... an animation with a series of steps, but some user interaction may require cancelling any remaining steps.

**Comment by leonoel** [comment]
`tlet` (via `then`) propagates cancellation signal to the task currently running.
For example, given this task
```
(def t
  (t/tlet [a (t/timeout 1000 6)
           b (t/timeout 1000 (inc a))]
    (prn :done)
    (* a b)))
```
The following code should not print `:done` :
```
(let [cancel! (t prn prn)]
  (Thread/sleep 1000)
  (cancel!))
```
Note that the task returned by `do!` has a 0-arity mapping the cancellation signal so you could as much have written this :
```
(let [cancel! (t/do! t)]
  (Thread/sleep 1000)
  (cancel!))
```
However, running it via `do!!` blocks the calling thread until task is completed so the only way to cancel it is to interrupt the calling thread with `Thread/interrupt`. `do!!` will intercept `InterruptedException` to trigger the task's cancellation signal.
So this should not print `:done` either :
```
(let [thread (Thread. #(t/do!! t))]
  (.start thread)
  (Thread/sleep 1000)
  (.interrupt thread))
```
Thread interruption on the JVM is a tricky subject and that's another good reason to avoid blocking calls as much as possible. I don't recommend using `do!!` outside of REPL experimentation or very exceptional situations such as the main function or shutdown hooks.

**Comment by timothypratley** [comment]
awesome, I really like this!

**Comment by timothypratley** [comment]
In ClojureScript:

```clj
(def t
  (t/tlet [a (t/timeout 1000
                        (doto :a (prn "A")))
           b (t/timeout 1000
                        (doto :b (prn "B")))
           c (t/timeout 1000
                        (doto :c (prn "C")))]
          [a b]))

(let [cancel! (t #(prn "SUCCESS" %) #(prn "FAIL" %))]
  (prn "CANCEL")
  (cancel!))
```

Produces:

```
:a "A"
core.cljs:182 "CANCEL"
core.cljs:182 "SUCCESS" nil
```

I like that B and C do not execute, but A still executes (probably because the timeout is not cancelled until invoked).

Cancelling the timeout could be achieved by storing the id returned by `js/setTimeout` and calling `js/clearTimeout`.

Also, does it make sense that cancelling results in SUCCESS? The chain was interrupted so it seems more like a FAIL... though it was interrupted intentionally, so I'm not really sure!!!???

**Comment by leonoel** [comment]
In your example, A is printed not as a side-effect of running the task, but as a side-effect of creating the task (you can check it by running t multiple times, B and C should be shown every time and A should not be shown at all).
It works this way because `tlet` first creates the task associated with the first binding (the timeout A), wraps the following computation (which depends on the result of the task) in a function, and then binds the task to the function.
So the first timeout task is actually cancelled right after being run, indeed via `clearTimeout` on cljs. As you can see, the [implementation](https://github.com/leonoel/task/blob/3f52d0430c3beed91354e9828bdb181108e3640c/src/task/host.cljs#L19-L21) of `timeout` is straightforward.

Your question about the result of a cancelled task is actually a design point I have not settled yet. I will open an issue to gather thoughts about this.

**Comment by timothypratley** [comment]
Ah I see. Thank you for the clarification.
